From f06ad511725b28d821532acae45a25d0a186fc9f Mon Sep 17 00:00:00 2001
From: John (J5) Palmieri <johnp@redhat.com>
Date: Wed, 09 Mar 2011 18:02:50 +0000
Subject: [gi-overrides] fix exception block so it works in Python 2.5

---
diff --git a/gi/overrides/Gio.py b/gi/overrides/Gio.py
index 20343a2..aa37784 100644
--- a/gi/overrides/Gio.py
+++ b/gi/overrides/Gio.py
@@ -23,6 +23,8 @@ from ..importer import modules
 
 from gi.repository import GLib
 
+import sys
+
 Gio = modules['Gio']._introspection_module
 
 __all__ = []
@@ -109,7 +111,8 @@ class _DBusProxyMethodCall:
         (result_callback, error_callback, real_user_data) = user_data
         try:
             ret = obj.call_finish(result)
-        except Exception as e:
+        except Exception:
+            etype, e = sys.exc_info()[:2]
             # return exception as value
             if error_callback:
                 error_callback(obj, e, real_user_data)
--
cgit v0.8.3.4
